# Azure pipeline definition for the integration of the solution (continuous integration)
# See: https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

schedules:
- cron: "0 0 * * *"
  displayName: 'Daily midnight build'
  branches:
    include:
    - master
  always: true

variables:
# library variable groups
- group: 'build-tools'
- group: 'integration-testing-sandbox'
# common task variables
- name: 'BuildConfiguration'
  value: 'Debug'
- name: 'SolutionFile'
  value: 'AlmOps.sln'
- name: 'TestProjects'
  value: 'test/*Tests/*.csproj'
# tool variables (Sonar)
- name: 'sonar.project.name'
  value: 'AlmOps'
- name: 'sonar.project.key'
  value: 'devpro.almops'

pool:
  # code coverage generation only works on Windows for the moment
  vmImage: 'windows-latest'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare code analysis'
  inputs:
    SonarCloud: '$(sonar.instance)'
    organization: '$(sonar.organization)'
    scannerMode: 'MSBuild'
    projectKey: '$(sonar.project.key)'
    projectName: '$(sonar.project.name)'
    extraProperties: |
      sonar.cpd.exclusions=**/Models/*.cs,**/Dto/*.cs
- task: DotNetCoreCLI@2
  displayName: 'Build the .NET solution'
  inputs:
    command: 'build'
    projects: $(SolutionFile)
    arguments: '-c $(BuildConfiguration)'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    COREHOST_TRACE: 0
- task: DotNetCoreCLI@2
  displayName: 'Run the .NET test projects'
  inputs:
    command: 'test'
    projects: $(TestProjects)
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    COREHOST_TRACE: 0
    AlmOps__Sandbox__Organization: $(almops.azuredevops.organization)
    AlmOps__Sandbox__Username: $(almops.azuredevops.username)
    AlmOps__Sandbox__Token: $(almops.azuredevops.token)
    AlmOps__Sandbox__Project: $(almops.azuredevops.project)
    AlmOps__Sandbox__VariableGroup: $(almops.azuredevops.demovariablegroup.id)
- task: SonarCloudAnalyze@1
  displayName: 'Analyze the code with Sonar'
- task: SonarCloudPublish@1
  displayName: 'Publish the code analysis results'
  inputs:
    pollingTimeoutSec: '300'
